- hosts: all
  gather_facts: false
  pre_tasks:
    - name: update pacman
      become: true
      raw: pacman -Syu --noconfirm

    - name: install python
      become: true
      raw: pacman -S python --noconfirm

  tasks:
    - name: install git
      become: true
      community.general.pacman:
        name:
          - git
          - openssh

    - include: tasks/ssh.yml
    - include: tasks/dotfiles.yml
    - include: tasks/zsh-setup.yml
