- name: download nvm
  url: https://raw.githubuser.com/nvm-sh/nvm/v0.39.1/install.sh
  dest: /tmp/install_nvm.sh
  mode: "0755"
  tags:
    - node

- name: install nvm
  shell: /tmp/install_nvm.sh
  tags:
    - node