- name: install system packages
  become: true
  community.general.pacman:
    name:
      - zsh
      - git
      - tig
      - base-devel
      - openssh
      - fzf
      - tmux
      - tree
      - stow
      - noto-fonts
  