- name: download installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: "yes"
  tags:
    - rust

- name: install rust
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust
