- name: install stow
  become: true
  community.general.pacman:
    name:
      - zsh

- name: Download antigen
  get_url:
    url: http://git.io/antigen
    dest: ~/.antigen.zsh

- name: Change shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
