---
- name: Download antigen
  get_url:
    url: http://git.io/antigen
    dest: ~/.antigen.zsh

- name: install git
  become: true
  community.general.pacman:
    name:
      - git

- name: checkout dotfiles
  ansible.builtin.git:
      repo: git@github.com:albertoide/dotfiles.git
      dest: ~/src/dotfiles
      accept_hostkey: yes

- name: install stow
  become: true
  community.general.pacman:
    name:
      - stow

- name: stow dotfiles
  ansible.builtin.command: 
      cmd: stow -t ${HOME} -d ${HOME}/src/dotfiles -S zsh tmux
